const moviesActions = {
  REQUEST_GET_MOVIES: 'REQUEST_GET_MOVIES',
  SUCCESS_GET_MOVIES: 'SUCCESS_GET_MOVIES',
  FAILURE_GET_MOVIES: 'FAILURE_GET_MOVIES',
  CLEAR_ALL_MOVIES: 'CLEAR_ALL_MOVIES',
  REQUEST_GET_MOVIE: 'REQUEST_GET_MOVIE',
  SUCCESS_GET_MOVIE: 'SUCCESS_GET_MOVIE',
  FAILURE_GET_MOVIE: 'FAILURE_GET_MOVIE',
};

export default moviesActions;